# Why Am I Doing This Project?

Customer churn is an important business problem because losing customers can directly affect a company's revenue and growth. The goal of this project is to analyze customer data and identify the factors that are associated with customer churn.

Through this project, I want to use Data Science and Machine Learning techniques to:

* Understand customer behavior and churn patterns.
* Clean and analyze real-world customer data.
* Identify important factors related to customer churn.
* Build and compare machine learning classification models.
* Predict whether a customer is likely to churn.
* Evaluate model performance using appropriate metrics such as Precision, Recall, F1-Score, and ROC-AUC.
* Identify important features that contribute to churn predictions.
* Deploy the final model using Streamlit.

This project will help me strengthen my practical skills in **Data Cleaning, EDA, Feature Engineering, Data Preprocessing, Machine Learning, Model Evaluation, and Deployment** while solving a realistic business problem.

# Dataset Description
The dataset contains information on telecom customers such as their demographics, usage patterns, and account information. The target variable is whether the customer churned (1) or not (0). The dataset has 7,043 observations and 20 input features.

* Customers who left within the last month – the column is called Churn
* Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
* Customer account information – how long they’ve been a customer, contract, payment method, paperless billing, monthly charges, and total charges
* Demographic info about customers – gender, age range, and if they have partners and dependents

Source: [Datset Link](https://www.kaggle.com/datasets/blastchar/telco-customer-churn?utm_source=chatgpt.com)

# Dataset Description

| **Variable**     | **Details**                                                               | **Data Type** |
| :----------------| :------------------------------------------------------------------------ | :-------: |
| customerID       | Unique ID assigned to each customer                                       |  object |
| gender           | Gender of the customer (Male, Female)                                     |  object |
| SeniorCitizen    | Whether the customer is a senior citizen (1 = Yes, 0 = No)                |  int64  |
| Partner          | Whether the customer has a partner (Yes, No)                              |  object |
| Dependents       | Whether the customer has dependents (Yes, No)                             |  object |
| tenure           | Number of months the customer has stayed with the company                 |  int64  |
| PhoneService     | Whether the customer has phone service (Yes, No)                          |  object |
| MultipleLines    | Whether the customer has multiple lines (Yes, No, No phone service)       |  object |
| InternetService  | Type of internet service (DSL, Fiber optic, No)                           |  object |
| OnlineSecurity   | Whether the customer has online security (Yes, No, No internet service)   |  object |
| OnlineBackup     | Whether the customer has online backup (Yes, No, No internet service)     |  object |
| DeviceProtection | Whether the customer has device protection (Yes, No, No internet service) |  object |
| TechSupport      | Whether the customer has technical support (Yes, No, No internet service) |  object |
| StreamingTV      | Whether the customer has streaming TV (Yes, No, No internet service)      |  object |
| StreamingMovies  | Whether the customer has streaming movies (Yes, No, No internet service)  |  object |
| Contract         | Contract term of the customer (Month-to-month, One year, Two year)        |  object |
| PaperlessBilling | Whether the customer uses paperless billing (Yes, No)                     |  object |
| PaymentMethod    | Customer's payment method                                                 |  object |
| MonthlyCharges   | Amount charged to the customer each month                                 | float64 |
| TotalCharges     | Total amount charged to the customer                                      |  object |
| Churn            | Whether the customer has churned (Yes, No)                                |  object |

# TASK #1: Import Libraries and Datasets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_validate,
    GridSearchCV
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay
)

In [ ]:
# Loading the dataset
tele_df = pd.read_csv("Telco_Customer_Churn_Dataset.csv")

# Task #2: Explore Dataset

In [ ]:
# Checking the dataset
tele_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
tele_df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
# Checking the shape
tele_df.shape

(7043, 21)

In [ ]:
tele_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
tele_df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000